dist: trusty
sudo: false
language: go
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
addons:
  apt:
    packages:
    - libpcap-dev
install: true
script:
  - ./check.bash
  - ./build.bash
  - ./test.bash
  - ./doc.bash
